### ISSUE TITLE
BTP ABAP Trial - Issue when linking any github.com repository

### ISSUE THREAD

**Issue by attilaberencsi** [abapGit/ADT_Frontend#227]
Hello ABAPGit Team,

when I am trying to connect from EU BTP ABAP Environment Trial(Shared instance) to any public github.com repository the operation: Linking repository is hanging forever after successfully selecting the proper branch and the Transport Request.

![image](https://user-images.githubusercontent.com/20442467/177570222-d7bf1731-945a-4b98-856e-fe0b13aa7930.png)

I checked the eclipse error log, and found the following:

Unhandled event loop exception

java.lang.NullPointerException: Cannot invoke "org.abapgit.adt.backend.model.abapgitrepositories.IRepository.getLinks()" because "repository" is null
at org.abapgit.adt.ui.internal.util.AbapGitService.isSelectivePullSupported(AbapGitService.java:76)
at org.abapgit.adt.ui.internal.repositories.AbapGitView.openSelectivePullWizard(AbapGitView.java:600)
at org.abapgit.adt.ui.internal.repositories.AbapGitView.access$9(AbapGitView.java:588)
at org.abapgit.adt.ui.internal.repositories.AbapGitView$16.run(AbapGitView.java:516)
at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
at org.eclipse.jface.action.ActionContributionItem.lambda$5(ActionContributionItem.java:453)
at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4068)
at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

Session data

eclipse.buildId=4.24.0.I20220607-0700
java.version=17.0.3
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=hu_HU
Framework arguments: -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product
Command-line arguments: -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product -data file:/C:/Users/attil/Work/Software/Working/ADT3/attila/ -product org.eclipse.epp.package.java.product

I tried to reinstall eclipse and ABAP Developer Tools + plus the ABAPGit plugin, and also use SAP Machine JDK instead of the built-in JAVA release, but no luck, still facing the issue.

I was able to pull repositories existing (added in January already) from github.com, the issue happens when adding new one only.

Can You please advise, is that because of some issue with the BTP ABAP Environment

![image](https://user-images.githubusercontent.com/20442467/177570631-b7c39fd8-0bf2-40df-8d21-1b1fe3f26e6f.png)

or my workstation or somehow related to the plugin ?

Thank You in advance
Kind regards, Attila

**Comment by shubhamWaghmare-sap** [comment]
Hi Attila,

I checked in the trial system but was not able to reproduce the issue and the linking was successful.
Could you provide more details to reproduce the issue?

The following information will also help.
1. Is the "Pull after link" checkbox checked in the "Branch and Package Selection" page?
2. After stopping/closing the wizard can you already see the repository as linked?
3. Screenshots of the wizard pages.

P.S. There doesn't seem to be any issue with the BTP ABAP Environment.

Regards
Shubham

**Comment by attilaberencsi** [comment]
Hi Shubham,
I am trying to pull the following repository:
https://github.com/attilaberencsi/feovp.git

Here is the video for reference:
https://abaper.synology.me:5001/sharing/H1RxAE5ur

Thank You, Attila

**Comment by shubhamWaghmare-sap** [comment]
Hi Atilla,

I still could not reproduce the issue with the repository https://github.com/attilaberencsi/feovp.git and the repository was linked successfully.
FYI, I tested in a trial instance for US region, as trial instances for EU are no longer available.

I would request for more information to figure out the issue and fix it.

1. After stopping/force closing the Link wizard, does the repository appear in the list in abapGIT repositories view? (manually refresh the view to be sure)
2. Is the link action successful in case the _"pull after link"_ checkbox is not selected?
![image](https://user-images.githubusercontent.com/57699330/179422178-23dfc5d1-794e-482c-9e56-614658f5ba91.png)

Current Diagnosis:
The **_clonedRepository_** that is to be pulled, is not retrieved successfully. This would suggest there's an issue with the utility to getRepositoryByURL or the link action for repository itself failed. Thus pull leads to NullPointerException.

https://github.com/abapGit/ADT_Frontend/blob/8ffd001f51cd9c11be60636dcd77f6cade617210/org.abapgit.adt.ui/src/org/abapgit/adt/ui/internal/repositories/AbapGitView.java#L590-L596

Current Solution:
Updated new version of abapGIT v1.6.5 to handle the NullPointerException elegantly.
After answering above queries,  please update and check with the new version and share the error messages (if any).

Regards
Shubham.
